/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Alert: typeof import('./components/common/Alert.vue')['default']
    AlertComponent: typeof import('./components/common/AlertComponent.vue')['default']
    AppFooter: typeof import('./components/common/AppFooter.vue')['default']
    AppNavBar: typeof import('./components/common/AppNavBar.vue')['default']
    CharacterCard: typeof import('./components/characters/CharacterCard.vue')['default']
    CharacterCardLoading: typeof import('./components/characters/CharacterCardLoading.vue')['default']
    CharacterDetail: typeof import('./components/characters/CharacterDetail.vue')['default']
    CharactersComponent: typeof import('./components/characters/CharactersComponent.vue')['default']
    EmptyResult: typeof import('./components/common/EmptyResult.vue')['default']
    EpisodesComponent: typeof import('./components/episodes/EpisodesComponent.vue')['default']
    ListCharacters: typeof import('./components/characters/ListCharacters.vue')['default']
    ListCharactersLoading: typeof import('./components/characters/ListCharactersLoading.vue')['default']
    LocationsComponent: typeof import('./components/locations/LocationsComponent.vue')['default']
    PaginationContent: typeof import('./components/common/PaginationContent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeToggler: typeof import('./components/common/ThemeToggler.vue')['default']
  }
}
