/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Alert: typeof import('./components/common/Alert.vue')['default']
    AlertComponent: typeof import('./components/common/AlertComponent.vue')['default']
    AppFooter: typeof import('./components/common/AppFooter.vue')['default']
    AppNavBar: typeof import('./components/common/AppNavBar.vue')['default']
    CharacterCard: typeof import('./components/characters/CharacterCard.vue')['default']
    CharacterCardLoading: typeof import('./components/characters/CharacterCardLoading.vue')['default']
    CharacterDetail: typeof import('./components/characters/characterDetail/CharacterDetail.vue')['default']
    CharacterDetailLoading: typeof import('./components/characters/characterDetail/CharacterDetailLoading.vue')['default']
    CharacterInfo: typeof import('./components/characters/characterDetail/CharacterInfo.vue')['default']
    CharacterLocations: typeof import('./components/characters/characterDetail/CharacterLocations.vue')['default']
    CharactersComponent: typeof import('./components/characters/CharactersComponent.vue')['default']
    EmptyResult: typeof import('./components/common/EmptyResult.vue')['default']
    EpisodeDetail: typeof import('./components/episodes/episodeDetail/EpisodeDetail.vue')['default']
    EpisodeDetailLoading: typeof import('./components/episodes/episodeDetail/EpisodeDetailLoading.vue')['default']
    EpisodesCard: typeof import('./components/episodes/EpisodesCard.vue')['default']
    EpisodesCardLoading: typeof import('./components/episodes/EpisodesCardLoading.vue')['default']
    EpisodesComponent: typeof import('./components/episodes/EpisodesComponent.vue')['default']
    ListCharacters: typeof import('./components/characters/ListCharacters.vue')['default']
    ListCharactersLoading: typeof import('./components/characters/ListCharactersLoading.vue')['default']
    ListEpisodes: typeof import('./components/episodes/ListEpisodes.vue')['default']
    ListLocations: typeof import('./components/locations/ListLocations.vue')['default']
    LocationDetail: typeof import('./components/locations/locationDetail/LocationDetail.vue')['default']
    LocationDetailLoading: typeof import('./components/locations/locationDetail/LocationDetailLoading.vue')['default']
    LocationsCard: typeof import('./components/locations/LocationsCard.vue')['default']
    LocationsCardLoading: typeof import('./components/locations/LocationsCardLoading.vue')['default']
    LocationsComponent: typeof import('./components/locations/LocationsComponent.vue')['default']
    PaginationContent: typeof import('./components/common/PaginationContent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeToggler: typeof import('./components/common/ThemeToggler.vue')['default']
  }
}
