/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/characters/': RouteRecordInfo<'/characters/', '/characters', Record<never, never>, Record<never, never>>,
    '/characters/characterDetail/CharacterDetail': RouteRecordInfo<'/characters/characterDetail/CharacterDetail', '/characters/characterDetail/CharacterDetail', Record<never, never>, Record<never, never>>,
    '/characters/characterDetail/CharacterDetailLoading': RouteRecordInfo<'/characters/characterDetail/CharacterDetailLoading', '/characters/characterDetail/CharacterDetailLoading', Record<never, never>, Record<never, never>>,
    '/characters/characterDetail/CharacterInfo': RouteRecordInfo<'/characters/characterDetail/CharacterInfo', '/characters/characterDetail/CharacterInfo', Record<never, never>, Record<never, never>>,
    '/characters/characterDetail/CharacterLocations': RouteRecordInfo<'/characters/characterDetail/CharacterLocations', '/characters/characterDetail/CharacterLocations', Record<never, never>, Record<never, never>>,
    '/characters/ListCharactersLoading': RouteRecordInfo<'/characters/ListCharactersLoading', '/characters/ListCharactersLoading', Record<never, never>, Record<never, never>>,
    '/episodes/episodeDetail/EpisodeDetail': RouteRecordInfo<'/episodes/episodeDetail/EpisodeDetail', '/episodes/episodeDetail/EpisodeDetail', Record<never, never>, Record<never, never>>,
    '/episodes/episodeDetail/EpisodeDetailLoading': RouteRecordInfo<'/episodes/episodeDetail/EpisodeDetailLoading', '/episodes/episodeDetail/EpisodeDetailLoading', Record<never, never>, Record<never, never>>,
    '/episodes/episodes': RouteRecordInfo<'/episodes/episodes', '/episodes/episodes', Record<never, never>, Record<never, never>>,
    '/episodes/ListEpisodesLoading': RouteRecordInfo<'/episodes/ListEpisodesLoading', '/episodes/ListEpisodesLoading', Record<never, never>, Record<never, never>>,
    '/locations/ListLocationsLoading': RouteRecordInfo<'/locations/ListLocationsLoading', '/locations/ListLocationsLoading', Record<never, never>, Record<never, never>>,
    '/locations/locationDetail/LocationDetail': RouteRecordInfo<'/locations/locationDetail/LocationDetail', '/locations/locationDetail/LocationDetail', Record<never, never>, Record<never, never>>,
    '/locations/locationDetail/LocationDetailLoading': RouteRecordInfo<'/locations/locationDetail/LocationDetailLoading', '/locations/locationDetail/LocationDetailLoading', Record<never, never>, Record<never, never>>,
    '/locations/locations': RouteRecordInfo<'/locations/locations', '/locations/locations', Record<never, never>, Record<never, never>>,
  }
}
